import Foundation

/// Core task model representing a single actionable item
public struct Task: Identifiable, Codable, Equatable {
    public let id: UUID
    public var title: String
    public var description: String
    public var sourceContent: String
    public var furtherDetails: String          // Editable OCR content
    public var screenshotId: UUID?             // Reference to stored screenshot
    public var assignedTo: String?             // Person/company assigned to this task
    public var timeEstimate: TimeEstimate
    public var priority: Priority
    public var status: TaskStatus
    public var kanbanColumn: KanbanColumn?
    public var createdAt: Date
    public var updatedAt: Date
    public var metadata: TaskMetadata
    
    public init(
        id: UUID = UUID(),
        title: String,
        description: String = "",
        sourceContent: String = "",
        furtherDetails: String = "",
        screenshotId: UUID? = nil,
        assignedTo: String? = nil,
        timeEstimate: TimeEstimate = .twenty,
        priority: Priority = .medium,
        status: TaskStatus = .pending,
        kanbanColumn: KanbanColumn? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        metadata: TaskMetadata = TaskMetadata()
    ) {
        self.id = id
        self.title = title
        self.description = description
        self.sourceContent = sourceContent
        self.furtherDetails = furtherDetails
        self.screenshotId = screenshotId
        self.assignedTo = assignedTo
        self.timeEstimate = timeEstimate
        self.priority = priority
        self.status = status
        self.kanbanColumn = kanbanColumn
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.metadata = metadata
    }
}

/// Time estimate options for tasks (in minutes)
public enum TimeEstimate: Int, Codable, CaseIterable, Equatable {
    case ten = 10
    case twenty = 20
    case forty = 40
    case sixty = 60
    case overSixty = 90  // Represents 60+ minutes
    
    public var displayName: String {
        switch self {
        case .ten: return "10 min"
        case .twenty: return "20 min"
        case .forty: return "40 min"
        case .sixty: return "60 min"
        case .overSixty: return "60+ min"
        }
    }
    
    public var minutes: Int { rawValue }
}

/// Priority levels for tasks
public enum Priority: Int, Codable, CaseIterable, Equatable, Comparable {
    case low = 1
    case medium = 2
    case mega = 3
    
    public var displayName: String {
        switch self {
        case .low: return "Low"
        case .medium: return "Medium"
        case .mega: return "Mega"
        }
    }
    
    public static func < (lhs: Priority, rhs: Priority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

/// Status of a task in its lifecycle
public enum TaskStatus: String, Codable, CaseIterable, Equatable {
    case pending
    case inProgress
    case completed
    case deferred
    case deleted      // Soft-deleted tasks
    
    public var displayName: String {
        switch self {
        case .pending: return "Pending"
        case .inProgress: return "In Progress"
        case .completed: return "Completed"
        case .deferred: return "Deferred"
        case .deleted: return "Deleted"
        }
    }
}

/// Kanban board columns for organizing tasks across lifecycle
public enum KanbanColumn: String, Codable, CaseIterable, Equatable {
    case backlog
    case inProgress
    case blocked
    case done
    case deleted      // Column for soft-deleted tasks
    
    public var displayName: String {
        switch self {
        case .backlog: return "Backlog"
        case .inProgress: return "In Progress"
        case .blocked: return "Blocked"
        case .done: return "Done"
        case .deleted: return "Deleted"
        }
    }
}

/// Metadata extracted from captured screen content
public struct TaskMetadata: Codable, Equatable {
    public var sender: String?
    public var recipient: String?
    public var subject: String?
    public var sourceApp: String?
    public var capturedAt: Date?
    public var keywords: [String]
    public var llmGeneratedTitle: Bool    // Indicates if title was auto-generated by LLM
    
    public init(
        sender: String? = nil,
        recipient: String? = nil,
        subject: String? = nil,
        sourceApp: String? = nil,
        capturedAt: Date? = nil,
        keywords: [String] = [],
        llmGeneratedTitle: Bool = false
    ) {
        self.sender = sender
        self.recipient = recipient
        self.subject = subject
        self.sourceApp = sourceApp
        self.capturedAt = capturedAt
        self.keywords = keywords
        self.llmGeneratedTitle = llmGeneratedTitle
    }
    
    /// Returns true if any metadata field has content
    public var hasContent: Bool {
        sender != nil || recipient != nil || subject != nil || !keywords.isEmpty
    }
}
